---
- hosts: ansible-test
  remote_user: root
  tasks:
  - name: Install apache2 package
    apt: pkg=apache2 state=latest update_cache=yes
    notify:
    - start apache2
  handlers:
    - name: start apache2
      service: name=apache2 state=started


