heat_template_version: 2013-05-23

description: Simple deploy two compute instance on FutureSystems with ports 22, 80, and 443 open

resources:
  heatEx1SecurityGroup:
    type: OS::Neutron::SecurityGroup
    properties:
      description: "Security group to open ports 22, 30, and 443"
      name: "heatEx1SecurityGroup"
      rules: [{"direction" : "ingress", "ethertype": "IPv4", "port_range_min": 22,  "port_range_max": 22,  "protocol" : "TCP"},
              {"direction" : "ingress", "ethertype": "IPv4", "port_range_min": 80,  "port_range_max": 80,  "protocol" : "TCP"},
              {"direction" : "ingress", "ethertype": "IPv4", "port_range_min": 443, "port_range_max": 443, "protocol" : "TCP"}]
  instance1:
    type: OS::Nova::Server
    properties:
      key_name: vfleet2210-key
      image: futuresystems/ubuntu-14.04
      flavor: m1.small
      security_groups: [ { get_resource: heatEx1SecurityGroup } ]
  instance2:
    type: OS::Nova::Server
    properties:
      key_name: vfleet2210-key
      image: futuresystems/ubuntu-14.04
      flavor: m1.small
      security_groups: [ { get_resource: heatEx1SecurityGroup } ]
